#if defined(CHIP_IMI_2280)
#ifndef __RESET_IMI_2280__
#define __RESET_IMI_2280__

#define reset_name	"reset"


#define IMI_SW_RST(bank, id)        ((bank << 5) + id)

#define ADC_PRST				IMI_SW_RST(0, 0)
#define CAMIF_RST				IMI_SW_RST(0, 1)
#define CPU_RST					IMI_SW_RST(0, 2)
#define DPU_PIX_RST0			IMI_SW_RST(0, 5)
#define DPU_PIX_RST1			IMI_SW_RST(0, 6)
#define DPU_PIX_RST2			IMI_SW_RST(0, 7)
#define DSP0_INTC_RST           IMI_SW_RST(0, 8)
#define DSP1_INTC_RST           IMI_SW_RST(0, 9)
#define FPE_AXI_RST    		    IMI_SW_RST(0, 10)
#define FPE_CORE_RST   		    IMI_SW_RST(0, 11)
#define FPE_PIX_RST    		    IMI_SW_RST(0, 12)
#define MBOX0_P_RST    			IMI_SW_RST(0, 13)
#define MBOX1_P_RST    			IMI_SW_RST(0, 14)
#define MBOX2_P_RST    			IMI_SW_RST(0, 15)
#define MUSB_RST   			    IMI_SW_RST(0, 16)
#define MUSB_RSTA  			    IMI_SW_RST(0, 17)
#define MUSB_RSTX  			    IMI_SW_RST(0, 18)
#define DPU_A_RST           	IMI_SW_RST(0, 19)
#define DPU_AHBSRAM0_RST        IMI_SW_RST(0, 20)
#define DPU_AHBSRAM1_RST        IMI_SW_RST(0, 21)
#define DPU_ARM0_RST            IMI_SW_RST(0, 22)
#define DPU_ARM1_RST            IMI_SW_RST(0, 23)
#define DPU_SLV_RST         	IMI_SW_RST(0, 24)
#define DPU_FAST_BUS_M_RST      IMI_SW_RST(0, 25)
#define DPU_FAST_BUS_S_RST      IMI_SW_RST(0, 26)
#define DPU_APB_RST         	IMI_SW_RST(0, 27)
#define DPU_REFSRAM_RST         IMI_SW_RST(0, 28)
#define SKT_AXI_RST		        IMI_SW_RST(0, 29)
#define SKT_PIX_RST    		    IMI_SW_RST(0, 30)
#define SKT_RST		            IMI_SW_RST(0, 31)

#define U0_AHB2APB_RST			IMI_SW_RST(1, 0)
#define U0_CFGBUS_RST			IMI_SW_RST(1, 1)
#define U0_CLKGEN_PRST			IMI_SW_RST(1, 2)
#define QSPI0_HRST				IMI_SW_RST(1, 3)
#define QSPI0_PRST				IMI_SW_RST(1, 4)
#define QSPI0_REF_RST			IMI_SW_RST(1, 5)
#define CSI0_IPI_RST			IMI_SW_RST(1, 6)
#define U0_DDR_ARST0			IMI_SW_RST(1, 7)
#define U0_DDR_ARST1	        IMI_SW_RST(1, 8)
#define U0_DDR_CTL_PRST         IMI_SW_RST(1, 9)
#define U0_DDR_CTL_RST		    IMI_SW_RST(1, 10)
#define U0_DDR_PHY_PWROKIN	    IMI_SW_RST(1, 11)
#define U0_DDR_PHY_RST 		    IMI_SW_RST(1, 12)
#define U0_DDR_PHY_PRST 		IMI_SW_RST(1, 13)
#define DMAC0_A_RST    			IMI_SW_RST(1, 14)
#define DSP0_CORE_RST           IMI_SW_RST(1, 15)
#define DSP0_GLOBAL_RST         IMI_SW_RST(1, 16)
#define DSP0_OECM_RST           IMI_SW_RST(1, 17)
#define DSP0_MISC_RST           IMI_SW_RST(1, 18)
#define DSP0_SYS_RST            IMI_SW_RST(1, 19)
#define I2S0_G_RST		        IMI_SW_RST(1, 20)
#define I2S0_P_RST		        IMI_SW_RST(1, 21)
#define FAST_BUS_RST            IMI_SW_RST(1, 22)
#define GPIO0_G_RST             IMI_SW_RST(1, 23)
#define GPIO0_P_RST         	IMI_SW_RST(1, 24)
#define U0_I2C_P_RST      		IMI_SW_RST(1, 25)
#define U0_I2C_RST		        IMI_SW_RST(1, 26)
#define ISP_H_RST	         	IMI_SW_RST(1, 27)
#define ISP_JPEG_RST         	IMI_SW_RST(1, 28)
#define ISP_RST		        	IMI_SW_RST(1, 29)
#define MST_BUS_RST    		    IMI_SW_RST(1, 30)
#define OCRAM_RST	            IMI_SW_RST(1, 31)

#define PMU_RST					IMI_SW_RST(2, 0)
#define PWM_P_RST				IMI_SW_RST(2, 1)
#define PWM_RST					IMI_SW_RST(2, 2)
#define ROM_H_RST				IMI_SW_RST(2, 3)
#define RST_GEN_P_RST			IMI_SW_RST(2, 4)
#define SDIO0_RST				IMI_SW_RST(2, 5)
#define SLOW_BUS_RST			IMI_SW_RST(2, 6)
#define SPI0_BnRST				IMI_SW_RST(2, 7)
#define SPI0_nRST	        	IMI_SW_RST(2, 8)
#define SPI0_nSSRST      	   	IMI_SW_RST(2, 9)
#define SYSCON_P_RST		    IMI_SW_RST(2, 10)
#define TIMER64_0_P_RST		    IMI_SW_RST(2, 11)
#define TIMER64_0_RST 		    IMI_SW_RST(2, 12)
#define TIMER0_P_RST 			IMI_SW_RST(2, 13)
#define TIMER32_0_0_RST  		IMI_SW_RST(2, 14)
#define TIMER32_0_1_RST         IMI_SW_RST(2, 15)
#define TIMER32_0_2_RST         IMI_SW_RST(2, 16)
#define TIMER32_0_3_RST         IMI_SW_RST(2, 17)
#define TIMER32_0_4_RST         IMI_SW_RST(2, 18)
#define TIMER32_0_5_RST         IMI_SW_RST(2, 19)
#define TIMER32_0_6_RST		    IMI_SW_RST(2, 20)
#define TIMER0_WDOG_RST	        IMI_SW_RST(2, 21)
#define UART0_P_RST	            IMI_SW_RST(2, 22)
#define UART0_RST	            IMI_SW_RST(2, 23)
#define USB3_A_RST          	IMI_SW_RST(2, 24)
#define USB3_P_RST          	IMI_SW_RST(2, 25)
#define USB_DEV_PHY_RST	        IMI_SW_RST(2, 26)
#define VI_DOMAIN_A_RST0       	IMI_SW_RST(2, 27)
#define VI_DOMAIN_A_RST1       	IMI_SW_RST(2, 28)
#define VI_DOMAIN_P_RST0       	IMI_SW_RST(2, 29)
#define CSI0_TOP_RST	    	IMI_SW_RST(2, 30)
#define CSI1_TOP_RST        	IMI_SW_RST(2, 31)

#define CSI2_TOP_RST			IMI_SW_RST(3, 0)
#define VI_DOMAIN_P_RST4		IMI_SW_RST(3, 1)
#define VIC0_H_RST				IMI_SW_RST(3, 2)
#define U1_AHB2APB_RST			IMI_SW_RST(3, 3)
#define CSI1_IPI_RST			IMI_SW_RST(3, 4)
#define DSP1_CORE_RST           IMI_SW_RST(3, 5)
#define DSP1_GLOBAL_RST         IMI_SW_RST(3, 6)
#define DSP1_OECM_RST           IMI_SW_RST(3, 7)
#define DSP1_MISC_RST           IMI_SW_RST(3, 8)
#define DSP1_SYS_RST            IMI_SW_RST(3, 9)
#define GPIO1_G_RST			    IMI_SW_RST(3, 10)
#define GPIO1_P_RST		    	IMI_SW_RST(3, 11)
#define U1_I2C_P_RST	 		IMI_SW_RST(3, 12)
#define U1_I2C_RST	 			IMI_SW_RST(3, 13)
#define PWM1_P_RST  			IMI_SW_RST(3, 14)
#define PWM1_RST	            IMI_SW_RST(3, 15)
#define SPI1_BnRST         		IMI_SW_RST(3, 16)
#define SPI1_nRST           	IMI_SW_RST(3, 17)
#define SPI1_nSSRST           	IMI_SW_RST(3, 18)
#define TIMER64_1_P_RST         IMI_SW_RST(3, 19)
#define TIMER1_P_RST		    IMI_SW_RST(3, 20)
#define TIMER32_1_0_RST  		IMI_SW_RST(3, 21)
#define TIMER32_1_1_RST         IMI_SW_RST(3, 22)
#define TIMER32_1_2_RST         IMI_SW_RST(3, 23)
#define TIMER32_1_3_RST         IMI_SW_RST(3, 24)
#define TIMER32_1_4_RST         IMI_SW_RST(3, 25)
#define TIMER32_1_5_RST         IMI_SW_RST(3, 26)
#define TIMER32_1_6_RST		    IMI_SW_RST(3, 27)
#define TIMER1_WDOG_RST       	IMI_SW_RST(3, 28)
#define UART1_P_RST		       	IMI_SW_RST(3, 29)
#define UART1_RST			    IMI_SW_RST(3, 30)
#define VIC1_H_RST		        IMI_SW_RST(3, 31)

#define U2_AHB2APB_H_RST		IMI_SW_RST(4, 0)
#define CSI2_IPI_RST			IMI_SW_RST(4, 1)
#define GPIO2_G_RST				IMI_SW_RST(4, 2)
#define GPIO2_P_RST				IMI_SW_RST(4, 3)
#define VIC2_H_RST				IMI_SW_RST(4, 4)
#define U3_AHB2APB_H_RST        IMI_SW_RST(4, 5)
#define VIC3_H_RST         		IMI_SW_RST(4, 6)
#define VIP8000_A_RST           IMI_SW_RST(4, 7)
#define VIP8000_C_RST           IMI_SW_RST(4, 8)
#define VIP8000_H_RST            IMI_SW_RST(4, 9)
#define VPU_AXI_RST         	IMI_SW_RST(4, 10)
#define VPU_FUNC0_RST           IMI_SW_RST(4, 11)
#define VPU_FPE_A_RST           IMI_SW_RST(4, 12)
#define VPU_FPE_P_RST           IMI_SW_RST(4, 13)
#define VPU_APB_RST         	IMI_SW_RST(4, 14)
#define VPU_FUNC1_RST           IMI_SW_RST(4, 15)


#endif/*__RESET_IMI_2280__*/
#endif/*CHIP_IMI_2280*/
