#ifndef __IRQS_H__
#define __IRQS_H__

#define NR_VIC_IRQS                 (128)
#define VIC_BITS                    (32)

#define VIC0_IRQ_START              (0)
#define VIC1_IRQ_START              (VIC0_IRQ_START + 32)
#define VIC2_IRQ_START              (VIC0_IRQ_START + 64)
#define VIC3_IRQ_START              (VIC0_IRQ_START + 96)

/*.......................  FPGA  .........................*/
#if !((defined TARGET_SRAM) || (defined TARGET_DDR))
#define IRQ_WATCH_DOG               (VIC0_IRQ_START + 0)
#define IRQ_GPIO_BANK_0             (VIC0_IRQ_START + 1)
#define IRQ_GPIO_BANK_1             (VIC0_IRQ_START + 2)
#define IRQ_GPIO_BANK_2             (VIC0_IRQ_START + 3)
#define IRQ_GPIO_BANK_3             (VIC0_IRQ_START + 4)
#define IRQ_GPIO_BANK_4             (VIC0_IRQ_START + 5)
#define IRQ_GPIO_BANK_5             (VIC0_IRQ_START + 6)
#define IRQ_MBOX0_A2B               (VIC0_IRQ_START + 7)
#define IRQ_MBOX0_B2A               (VIC0_IRQ_START + 8)
#define IRQ_TIMER_0                 (VIC0_IRQ_START + 9)
#define IRQ_TIMER_1                 (VIC0_IRQ_START + 10)
#define IRQ_TIMER_2                 (VIC0_IRQ_START + 11)
#define IRQ_TIMER_3                 (VIC0_IRQ_START + 12)
#define IRQ_SPI0_TX                 (VIC0_IRQ_START + 13)
#define IRQ_SPI0_RX                 (VIC0_IRQ_START + 14)
#define IRQ_SPI0_RX_OVERRUN         (VIC0_IRQ_START + 15)
#define IRQ_I2C_0                   (VIC0_IRQ_START + 16)
#define IRQ_I2C_1                   (VIC0_IRQ_START + 17)
#define IRQ_UART0_TX                (VIC0_IRQ_START + 18)
#define IRQ_UART0_RX                (VIC0_IRQ_START + 19)
#define IRQ_UART0_RX_TIMEOUT        (VIC0_IRQ_START + 20)
#define IRQ_UART0_ERR               (VIC0_IRQ_START + 21)
#define IRQ_UART1_TX                (VIC0_IRQ_START + 22)
#define IRQ_UART1_RX                (VIC0_IRQ_START + 23)
#define IRQ_UART1_RX_TIMEOUT        (VIC0_IRQ_START + 24)
#define IRQ_UART1_ERR               (VIC0_IRQ_START + 25)
#define IRQ_I2C_2                   (VIC0_IRQ_START + 26)
#define IRQ_I2C_3                   (VIC0_IRQ_START + 27)
#define IRQ_SPI1_TX                 (VIC0_IRQ_START + 28)
#define IRQ_SPI1_RX                 (VIC0_IRQ_START + 29)
#define IRQ_SPI1_RX_OVERRUN         (VIC0_IRQ_START + 30)
#define IRQ_I2C_4                   (VIC0_IRQ_START + 31)


#define IRQ_DMA_0                   (VIC1_IRQ_START + 0)
#define IRQ_DMA_1                   (VIC1_IRQ_START + 1)
#define IRQ_DMA_2                   (VIC1_IRQ_START + 2)
#define IRQ_DMA_3                   (VIC1_IRQ_START + 3)
#define IRQ_DMA_4                   (VIC1_IRQ_START + 4)
#define IRQ_DMA_5                   (VIC1_IRQ_START + 5)
#define IRQ_DMA_6                   (VIC1_IRQ_START + 6)
#define IRQ_DMA_7                   (VIC1_IRQ_START + 7)
#define IRQ_DMA_8                   (VIC1_IRQ_START + 8)
#define IRQ_DMA_9                   (VIC1_IRQ_START + 9)
#define IRQ_DMA_10                  (VIC1_IRQ_START + 10)
#define IRQ_DMA_11                  (VIC1_IRQ_START + 11)
#define IRQ_DMA_12                  (VIC1_IRQ_START + 12)
#define IRQ_DMA_13                  (VIC1_IRQ_START + 13)
#define IRQ_DMA_14                  (VIC1_IRQ_START + 14)
#define IRQ_DMA_15                  (VIC1_IRQ_START + 15)
#define IRQ_DMA_ABORT               (VIC1_IRQ_START + 16)
#define IRQ_QSPI                    (VIC1_IRQ_START + 17)
#define IRQ_USB_DEV                 (VIC1_IRQ_START + 18)
#define IRQ_USB_DMA_INTR            (VIC1_IRQ_START + 19)
#define IRQ_USB_SOF_PLUSE           (VIC1_IRQ_START + 20)
#define IRQ_MIPI_TX0                (VIC1_IRQ_START + 25)
#define IRQ_MIPI_TX1                (VIC1_IRQ_START + 27)

#define IRQ_ISP_INT0                (VIC2_IRQ_START + 0)    //isp irq
#define IRQ_ISP_INT1                (VIC2_IRQ_START + 1)    //fe irq
#define IRQ_ISP_INT2                (VIC2_IRQ_START + 2)    //MI irq
#define IRQ_VPU_HOST                (VIC2_IRQ_START + 16)
#define IRQ_VPU_JPG                 (VIC2_IRQ_START + 17)
#define IRQ_G2D_INT0                (VIC2_IRQ_START + 20)
#define IRQ_G2D_INT1                (VIC2_IRQ_START + 21)
#define IRQ_G2D_INT2                (VIC2_IRQ_START + 22)
#define IRQ_G2D_INT3                (VIC2_IRQ_START + 23)
#define IRQ_MIPI_RX0_CTRL           (VIC2_IRQ_START + 24)
#define IRQ_MIPI_RX0_IPI            (VIC2_IRQ_START + 25)
#define IRQ_MIPI_RX1_CTRL           (VIC2_IRQ_START + 28)
#define IRQ_MIPI_RX1_IPI            (VIC2_IRQ_START + 29)

#define IRQ_DPU_FPP                 (VIC3_IRQ_START + 0)
#define IRQ_DPU_PIPILINE            (VIC3_IRQ_START + 1)
#define IRQ_DPU_DPETH_PKT           (VIC3_IRQ_START + 2)
#define IRQ_DPU_SHIFT_PKT           (VIC3_IRQ_START + 3)
#define IRQ_DPU_TRIGGER_IR          (VIC3_IRQ_START + 4)
#define IRQ_DPU_TRIGER_GS           (VIC3_IRQ_START + 5)
#define IRQ_DPU_TRIGER_VCSEL1       (VIC3_IRQ_START + 6)
#define IRQ_DPU                     (VIC3_IRQ_START + 7)
#define IRQ_RVL                     (VIC3_IRQ_START + 8)
#define IRQ_MPU_0                   (VIC3_IRQ_START + 28)
#define IRQ_MPU_1                   (VIC3_IRQ_START + 29)
#define IRQ_MPU_2                   (VIC3_IRQ_START + 30)
//gpio irq is gpio_num + NR_VIC_IRQS
#define IRQ_GPIO_NUM(n)             (NR_VIC_IRQS + n)

/*.......................  IMI2280  .........................*/
#else
#define IRQ_DDRC                    (VIC0_IRQ_START + 0)
#define IRQ_DFI_ERR                 (VIC0_IRQ_START + 1)
#define IRQ_MBOX0_A2B               (VIC0_IRQ_START + 2)
#define IRQ_MBOX0_B2A               (VIC0_IRQ_START + 3)
#define IRQ_MBOX1_A2B               (VIC0_IRQ_START + 4)
#define IRQ_MBOX1_B2A               (VIC0_IRQ_START + 5)
#define IRQ_MBOX2_A2B               (VIC0_IRQ_START + 6)
#define IRQ_CSI0_PHY                (VIC0_IRQ_START + 7)
#define IRQ_CSI1_PHY                (VIC0_IRQ_START + 8)
#define IRQ_CSI2_PHY                (VIC0_IRQ_START + 9)
#define IRQ_MBOX2_B2A               (VIC0_IRQ_START + 10)
#define IRQ_U0_TIMER64              (VIC0_IRQ_START + 11)
#define IRQ_U1_TIMER64              (VIC0_IRQ_START + 12)
#define IRQ_CMIF                    (VIC0_IRQ_START + 13)
#define IRQ_FPE                     (VIC0_IRQ_START + 14)
#define IRQ_MIPI                    (VIC0_IRQ_START + 15)
#define IRQ_MI                      (VIC0_IRQ_START + 16)
#define IRQ_ISP                     (VIC0_IRQ_START + 17)
#define IRQ_JPEG_ERR                (VIC0_IRQ_START + 18)
#define IRQ_JPEG_STAT               (VIC0_IRQ_START + 19)
#define IRQ_SKT_BPC                 (VIC0_IRQ_START + 20)
#define IRQ_SKT_CENTROID            (VIC0_IRQ_START + 21)
#define IRQ_SKT_FLOOR               (VIC0_IRQ_START + 22)
#define IRQ_SKT_FDIFF_FRAME         (VIC0_IRQ_START + 23)
#define IRQ_DKT_FDIFF_OVF           (VIC0_IRQ_START + 24)
#define IRQ_SKT_BLOB                (VIC0_IRQ_START + 25)
#define IRQ_USB3_DRD_0              (VIC0_IRQ_START + 26)
#define IRQ_USB3_DRD_1              (VIC0_IRQ_START + 27)
#define IRQ_USB3_DRD_2              (VIC0_IRQ_START + 28)
#define IRQ_USB3_HOST_SYS_ERR       (VIC0_IRQ_START + 29)
#define IRQ_VPU_HOST                (VIC0_IRQ_START + 30)
#define IRQ_VPU_JPG                 (VIC0_IRQ_START + 31)

#define IRQ_U0_MUSBNSFC_SOF_PLUSE   (VIC1_IRQ_START + 0)
#define IRQ_U0_MUSBHSFC_MC          (VIC1_IRQ_START + 1)
#define IRQ_U0_MUSBHSFC_DMA         (VIC1_IRQ_START + 2)
#define IRQ_U0_I2C                  (VIC1_IRQ_START + 3)
#define IRQ_U1_I2C                  (VIC1_IRQ_START + 4)
#define IRQ_U2_I2C                  (VIC1_IRQ_START + 5)
#define IRQ_U0_DW_I2S               (VIC1_IRQ_START + 6)
#define IRQ_DMA_ABORT               (VIC1_IRQ_START + 11)
#define IRQ_DMA_0                   (VIC1_IRQ_START + 12)
#define IRQ_DMA_1                   (VIC1_IRQ_START + 13)
#define IRQ_DMA_2                   (VIC1_IRQ_START + 14)
#define IRQ_DMA_3                   (VIC1_IRQ_START + 15)
#define IRQ_DMA_4                   (VIC1_IRQ_START + 16)
#define IRQ_DMA_5                   (VIC1_IRQ_START + 17)
#define IRQ_DMA_6                   (VIC1_IRQ_START + 18)
#define IRQ_DMA_7                   (VIC1_IRQ_START + 19)
#define IRQ_DMA_8                   (VIC1_IRQ_START + 20)
#define IRQ_DMA_9                   (VIC1_IRQ_START + 21)
#define IRQ_DMA_10                  (VIC1_IRQ_START + 22)
#define IRQ_DMA_11                  (VIC1_IRQ_START + 23)
#define IRQ_DMA_12                  (VIC1_IRQ_START + 24)
#define IRQ_DMA_13                  (VIC1_IRQ_START + 25)
#define IRQ_DMA_14                  (VIC1_IRQ_START + 26)
#define IRQ_DMA_15                  (VIC1_IRQ_START + 27)
#define IRQ_U0_UART                 (VIC1_IRQ_START + 28)
#define IRQ_U1_UART                 (VIC1_IRQ_START + 29)
#define IRQ_U0_SPI_SSP              (VIC1_IRQ_START + 30)
#define IRQ_U1_SPI_SSP              (VIC1_IRQ_START + 31)

#define IRQ_U0_TIMER_0              (VIC2_IRQ_START + 0)
#define IRQ_U0_TIMER_1              (VIC2_IRQ_START + 1)
#define IRQ_U0_TIMER_2              (VIC2_IRQ_START + 2)
#define IRQ_U0_TIMER_3              (VIC2_IRQ_START + 3)
#define IRQ_U0_TIMER_WDOG           (VIC2_IRQ_START + 4)
#define IRQ_U0_TIMER_5              (VIC2_IRQ_START + 5)
#define IRQ_U0_TIMER_6              (VIC2_IRQ_START + 6)
#define IRQ_U0_TIMER_7              (VIC2_IRQ_START + 7)
#define IRQ_U0_TIMER                (VIC2_IRQ_START + 8)
#define IRQ_U0_TIMER_FIQ            (VIC2_IRQ_START + 9)
#define IRQ_U1_TIMER_0              (VIC2_IRQ_START + 10)
#define IRQ_U1_TIMER_1              (VIC2_IRQ_START + 11)
#define IRQ_U1_TIMER_2              (VIC2_IRQ_START + 12)
#define IRQ_U1_TIMER_3              (VIC2_IRQ_START + 13)
#define IRQ_U1_TIMER_WDOG           (VIC2_IRQ_START + 14)
#define IRQ_U1_TIMER_5              (VIC2_IRQ_START + 15)
#define IRQ_U1_TIMER_6              (VIC2_IRQ_START + 16)
#define IRQ_U1_TIMER_7              (VIC2_IRQ_START + 17)
#define IRQ_U1_TIMER                (VIC2_IRQ_START + 18)
#define IRQ_U1_TIMER_FIQ            (VIC2_IRQ_START + 19)
#define IRQ_U0_GPIO                 (VIC2_IRQ_START + 20)
#define IRQ_U1_GPIO                 (VIC2_IRQ_START + 21)
#define IRQ_U2_GPIO                 (VIC2_IRQ_START + 22)
#define IRQ_ISP_ALL                 (VIC2_IRQ_START + 23)
#define IRQ_CQSPI                   (VIC2_IRQ_START + 24)
#define IRQ_SDIO                    (VIC2_IRQ_START + 24)
#define IRQ_XAQ2                    (VIC2_IRQ_START + 25)

#define IRQ_NJTOP_DPU               (VIC3_IRQ_START + 0)
/*
#define IRQ_NJTOP_MBOX_A2B0         (VIC3_IRQ_START + 1)  1~4
#define IRQ_NJTOP_MBOX_B2A0         (VIC3_IRQ_START + 5)  1~4
*/
#define IRQ_NJTOP_FPP				(VIC3_IRQ_START + 21)
#define IRQ_NJTOP_UVC_DEPTH			(VIC3_IRQ_START + 22)
#define IRQ_NJTOP_UVC_SHIFT			(VIC3_IRQ_START + 23)
#define IRQ_NJTOP_UVC_IR			(VIC3_IRQ_START + 24)
#define IRQ_NJTOP_SS0_TRIG			(VIC3_IRQ_START + 25)
#define IRQ_NJTOP_SS1_TRIG			(VIC3_IRQ_START + 26)
#define IRQ_NJTOP_SS2_TRIG			(VIC3_IRQ_START + 27)
#endif

#endif
